//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameSessions
    {
        public int GameSessionId { get; set; }
        public int UserId { get; set; }
        public int Score { get; set; }
        public int Level { get; set; }
        public int LinesCleared { get; set; }
        public int DurationSeconds { get; set; }
        public System.DateTime StartedAt { get; set; }
        public Nullable<System.DateTime> EndedAt { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
