//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSettings
    {
        public int UserSettingsId { get; set; }
        public int UserId { get; set; }
        public int BoardWidth { get; set; }
        public int BoardHeight { get; set; }
        public int StartingLevel { get; set; }
        public string Theme { get; set; }
        public bool IsSoundEnabled { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
